### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Leonime** [AzazeII/Applied-Integrations#11] opened 2019-03-19 06:04 UTC
It was a fresh install, first run, disabling the mod fixes the crash.
https://paste.dimdev.org/ojazofupir.mccrash

**Comment by AzazeII** [comment] 2019-03-19 11:25
Wait for new update, this bug already fixed in it. Crash caused by null sprite for fluid class

**Closed** 2019-03-19 11:25 UTC
