### ISSUE TITLE
ME interface

### ISSUE THREAD

**Issue by WardenCommander** [AzazeII/Applied-Integrations#21] opened 2019-12-16 21:32 UTC
ME interface has a small bug

I connect it to a solar panel that produce EU power, but interface shows RF
 
![Untitled](https://user-images.githubusercontent.com/46477089/70944740-fa2f4e00-2053-11ea-9756-e2cf55566ba6.png)

**Comment by indiscrete-void** [comment] 2019-12-16 21:36
Do you using last version ? What version of minecraft are you using ? Please fill issue from template on GitHub. 
If you are using last version and facing this issue: It'll not show energy in EU until you provide any EU to it, it's not a bug. Another thing if you connect it to solar panel, but it doesn't accept energy from it.

**Comment by WardenCommander** [comment] 2019-12-16 21:42
Im using:
Forge 1.12.2 - 14.23.5.2838
appliedenergistics2-rv6-stable-7
this mod latest version

Solar panels are from mod:
Advanced+Solar+Panels-4.3.0

ME interface accept power from it as it shows in cell
![Untitled](https://user-images.githubusercontent.com/46477089/70945314-34e5b600-2055-11ea-9b1b-e0e193337fd2.png)

also ME interface doesnt want to export power to machine that use EU power. Is this intended?

**Comment by indiscrete-void** [comment] 2019-12-16 21:47
I think this issue is related to that fact energy type is only changes when GUI see energy is filled, but in this example energy is immediately goes into cell and GUI doesn't see it.
> also ME interface doesnt want to export power to machine that use EU power. Is this intended?

This behaviour is caused by concept of interface, a machine that only provide/consume matter. It should not push energy into other machines, it should wait for machines to pull it from interface. On the other hand, not any machine and even cable pulls energy from interface. This behaviour may change in some version. Still undecided how to implement it better.

**Comment by WardenCommander** [comment] 2019-12-16 21:57
Another issue is that after right clicking it with wrench it forgets texture, also when you pick it up

new one are ok till you place it at power source or machine, but when you pick it up it goes like this

![Untitled](https://user-images.githubusercontent.com/46477089/70946271-30220180-2057-11ea-9143-150d938642f8.png)

**Comment by indiscrete-void** [comment] 2019-12-16 21:57
it is another known issue

**Comment by WardenCommander** [comment] 2019-12-16 21:59
> This behaviour is caused by concept of interface, a machine that only provide/consume matter. It should not push energy into other machines, it should wait for machines to pull it from interface. On the other hand, not any machine and even cable pulls energy from interface. This behaviour may change in some version. Still undecided how to implement it better.

im using it on IC2 machines, if it helps

**Comment by indiscrete-void** [comment] 2019-12-17 18:22
Fixed in dev version

**Closed as completed by indiscrete-void** 2019-12-17 18:22 UTC
Labels: bug

**Comment by WardenCommander** [comment] 2019-12-18 15:48
Could you update curseforge version as well

**Comment by indiscrete-void** [comment] 2019-12-18 15:48
Sometime later, there is another issue i want to fix in new CF version

**Comment by indiscrete-void** [comment] 2019-12-19 16:21
https://www.curseforge.com/minecraft/mc-mods/applied-integrations/files/2845344

**Comment by WardenCommander** [comment] 2019-12-20 18:59
> ME interface has a small bug
> 
> I connect it to a solar panel that produce EU power, but interface shows RF

Tested this is working, great work 👍

**Comment by WardenCommander** [comment] 2019-12-20 19:04
> Another issue is that after right clicking it with wrench it forgets texture, also when you pick it up
 this is also fixed 👍 

 
> ![Untitled](https://user-images.githubusercontent.com/46477089/70946271-30220180-2057-11ea-9143-150d938642f8.png)

this is still happening when you remove it from power source.

also when i re attach Interface back to power source, interface storage in interface shows 
minus some power, -XXX/250000 EU, XXX depending how long interface was not attached on power source, then first raise number to 0, then push power to cell.

**Comment by indiscrete-void** [comment] 2019-12-21 23:22
Got what is wrong. When interface injects energy this chain fires:
Check what energy would be injected if it'll inject currently stored amount in network -> Check what energy would be extracted if it'll extract current stored amount from it's energy storage -> Modulate extraction and injection. 
This issue only happens with EU because it doesn't have this "simulation" method. When interface trying to check what energy it can extract, it really extracts this amount from EU storage, so when it modulates extraction, it extracts this energy second time so it goes to minus values...

**Comment by indiscrete-void** [comment] 2019-12-21 23:52
New version on CF - https://www.curseforge.com/minecraft/mc-mods/applied-integrations/files/2846570
